#defaults:
#  - _self_
#  - override hydra/hydra_logging: disabled  
#  - override hydra/job_logging: disabled

fast_dev_run: false

#hydra:
#  output_subdir: null  # Lightning already handles output directories
#  run:
#    dir: .  # Do not change dir

log:
  save_dir: './logs'
  freq: 50  # Log to W&B every X steps

wandb:
  project: 'vlr-project'

data_dir: '/data/group_data/neuroagents_lab/training_datasets/imagenet_raw/train'
# The image_paths_pkl file contains the sub-paths to each image in data_dir.
image_paths_pkl: './imagenet_train_paths.pkl'

# Will resize & crop every image to this size, then divide into patches.
image_size: 256  
num_puzzle_patches: 64

# We use a (fixed) random subset of the ImageNet dataset for training.
rand_subset_size: 10000
rand_subset_seed: 42

train_percent: 0.8
val_percent: 0.2
num_workers: 4

num_epochs: 100
batch_size: 32
learning_rate: 1e-3

